sudo: false
language: php
matrix:
  fast_finish: true
  include:
    - php: '7.0'
    - php: '7.1'
    - php: hhvm
      sudo: true
      dist: trusty
      env: HHVMPHP7="yes"
php:
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

before_script:
  - composer install --ignore-platform-reqs
  - if [[ $HHVMPHP7 == "yes" ]]; then echo hhvm.php7.all=1 >> /etc/hhvm/php.ini; fi

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit
