language: php
sudo: false

matrix:
  - php: 7.0
  - php: 7.7
  - php: hhvm
    sudo: true
    dist: trusty
    env: HHVMPHP7 = "yes"

before_script:
  - if [[ $HHVMPHP7 == "yes" ]]; then echo hhvm.php7.all=1 >> /etc/hhvm/php.ini; fi
  - if [[ $HHVMPHP7 == "yes" ]]; then composer install --ignore-platform-reqs; else composer install; fi

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit
